# Generated by Django 3.2.8 on 2021-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('pr_data', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('deck', models.TextField()),
            ],
        ),
    ]
